name: Epics workflow
on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled]
jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'subepic')
    runs-on: ubuntu-latest
    steps:
    - name: Update parent issues
      uses: ribtoks/parent-issue-update@master
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
